name: SSH Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Sleep for 10 minutes
        run: sleep 600
